# Generated by Django 5.1.5 on 2025-02-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='waitlist',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='mbti',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='partner_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='preference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='social_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
